import {
  Cloud,
  Cpu,
  Database,
  Globe,
  MonitorSmartphone,
  Server,
  Shield,
  Smartphone,
} from "lucide-react";

import type { ProjectData } from "../types";

export const ECOMMERCE_SAAS: ProjectData = {
  id: "ecommerce-saas",
  nodes: [
    {
      id: "browser",
      icon: Globe,
      tech: ["React 19", "Next.js"],
      x: 5,
      y: 10,
      connections: ["nextjs"],
      group: "client",
    },
    {
      id: "mobile",
      icon: Smartphone,
      tech: ["React Native", "Expo"],
      x: 5,
      y: 55,
      connections: ["api"],
      group: "client",
    },
    {
      id: "nextjs",
      icon: MonitorSmartphone,
      tech: ["App Router", "RSC", "Server Actions"],
      x: 30,
      y: 10,
      connections: ["api", "auth"],
      group: "server",
    },
    {
      id: "api",
      icon: Server,
      tech: ["tRPC", "Zod", "REST"],
      x: 30,
      y: 55,
      connections: ["db", "cache", "auth"],
      group: "server",
    },
    {
      id: "auth",
      icon: Shield,
      tech: ["NextAuth.js", "JWT", "OAuth"],
      x: 57,
      y: 10,
      connections: ["db"],
      group: "server",
    },
    {
      id: "db",
      icon: Database,
      tech: ["PostgreSQL", "Prisma"],
      x: 57,
      y: 55,
      connections: [],
      group: "data",
    },
    {
      id: "cache",
      icon: Cpu,
      tech: ["Redis", "Upstash"],
      x: 82,
      y: 10,
      connections: [],
      group: "data",
    },
    {
      id: "deploy",
      icon: Cloud,
      tech: ["Vercel", "GitHub Actions"],
      x: 82,
      y: 55,
      connections: [],
      group: "infra",
    },
  ],
};
