import {
  Bell,
  CreditCard,
  Database,
  MapPin,
  Server,
  Shield,
  Shuffle,
  Smartphone,
} from "lucide-react";

import type { ProjectData } from "../types";

export const RIDE_SHARING: ProjectData = {
  id: "ride-sharing",
  nodes: [
    {
      id: "mobile",
      icon: Smartphone,
      tech: ["React Native", "WebSocket", "Maps SDK"],
      x: 5,
      y: 10,
      connections: ["gateway"],
      group: "client",
    },
    {
      id: "gateway",
      icon: Shield,
      tech: ["Node.js", "JWT", "Rate Limit"],
      x: 30,
      y: 10,
      connections: ["matching", "location", "pricing"],
      group: "server",
    },
    {
      id: "matching",
      icon: Shuffle,
      tech: ["Python", "Geohash", "Dijkstra"],
      x: 57,
      y: 10,
      connections: ["notif", "db"],
      group: "server",
    },
    {
      id: "payments",
      icon: CreditCard,
      tech: ["Stripe", "Fraud Detection", "Idempotency"],
      x: 82,
      y: 10,
      connections: ["db"],
      group: "server",
    },
    {
      id: "location",
      icon: MapPin,
      tech: ["Redis Geo", "WebSocket", "Geohash"],
      x: 5,
      y: 55,
      connections: ["matching", "db"],
      group: "server",
    },
    {
      id: "pricing",
      icon: Server,
      tech: ["Python", "Surge Algorithm", "ML"],
      x: 30,
      y: 55,
      connections: ["matching", "payments"],
      group: "server",
    },
    {
      id: "notif",
      icon: Bell,
      tech: ["Firebase FCM", "APNs", "SMS"],
      x: 57,
      y: 55,
      connections: [],
      group: "server",
    },
    {
      id: "db",
      icon: Database,
      tech: ["PostgreSQL", "PostGIS", "Redis"],
      x: 82,
      y: 55,
      connections: [],
      group: "data",
    },
  ],
};
