import {
  Activity,
  Bell,
  Cpu,
  Database,
  Image,
  Server,
  Shield,
  Smartphone,
} from "lucide-react";

import type { ProjectData } from "../types";

export const SOCIAL_FEED: ProjectData = {
  id: "social-feed",
  nodes: [
    {
      id: "mobile",
      icon: Smartphone,
      tech: ["React Native", "GraphQL", "Apollo"],
      x: 5,
      y: 10,
      connections: ["gateway"],
      group: "client",
    },
    {
      id: "gateway",
      icon: Shield,
      tech: ["GraphQL", "DataLoader", "JWT"],
      x: 30,
      y: 10,
      connections: ["feed", "media"],
      group: "server",
    },
    {
      id: "feed",
      icon: Server,
      tech: ["Node.js", "Fan-out on Write", "Redis"],
      x: 57,
      y: 10,
      connections: ["cache", "db"],
      group: "server",
    },
    {
      id: "cache",
      icon: Cpu,
      tech: ["Redis", "Sorted Sets", "TTL"],
      x: 82,
      y: 10,
      connections: [],
      group: "data",
    },
    {
      id: "notif",
      icon: Bell,
      tech: ["Firebase FCM", "APNs", "WebSocket"],
      x: 5,
      y: 55,
      connections: [],
      group: "server",
    },
    {
      id: "queue",
      icon: Activity,
      tech: ["RabbitMQ", "SQS", "Dead Letter"],
      x: 30,
      y: 55,
      connections: ["notif"],
      group: "infra",
    },
    {
      id: "media",
      icon: Image,
      tech: ["S3", "CloudFront", "Sharp"],
      x: 57,
      y: 55,
      connections: ["queue", "db"],
      group: "server",
    },
    {
      id: "db",
      icon: Database,
      tech: ["Cassandra", "Sharding", "CQL"],
      x: 82,
      y: 55,
      connections: [],
      group: "data",
    },
  ],
};
