import {
  Cloud,
  Cpu,
  Database,
  Globe,
  HardDrive,
  Server,
  Sparkles,
  Upload,
} from "lucide-react";

import type { ProjectData } from "../types";

export const VIDEO_STREAMING: ProjectData = {
  id: "video-streaming",
  nodes: [
    {
      id: "browser",
      icon: Globe,
      tech: ["HLS.js", "MSE", "Adaptive Bitrate"],
      x: 5,
      y: 10,
      connections: ["cdn", "api", "upload"],
      group: "client",
    },
    {
      id: "cdn",
      icon: Cloud,
      tech: ["CloudFront", "HLS/DASH", "Edge Cache"],
      x: 30,
      y: 10,
      connections: [],
      group: "infra",
    },
    {
      id: "api",
      icon: Server,
      tech: ["Node.js", "REST", "GraphQL"],
      x: 57,
      y: 10,
      connections: ["recommend", "db"],
      group: "server",
    },
    {
      id: "recommend",
      icon: Sparkles,
      tech: ["Python", "TensorFlow", "Collaborative"],
      x: 82,
      y: 10,
      connections: ["db"],
      group: "server",
    },
    {
      id: "upload",
      icon: Upload,
      tech: ["Chunked Upload", "Resumable", "tus"],
      x: 5,
      y: 55,
      connections: ["transcode"],
      group: "server",
    },
    {
      id: "transcode",
      icon: Cpu,
      tech: ["FFmpeg", "GPU Workers", "H.264/H.265"],
      x: 30,
      y: 55,
      connections: ["storage"],
      group: "infra",
    },
    {
      id: "storage",
      icon: HardDrive,
      tech: ["S3", "GCS", "Multipart"],
      x: 57,
      y: 55,
      connections: ["cdn"],
      group: "data",
    },
    {
      id: "db",
      icon: Database,
      tech: ["MySQL", "Bigtable", "Metadata"],
      x: 82,
      y: 55,
      connections: [],
      group: "data",
    },
  ],
};
